import { Meal, SubscriptionPlan, Order, User, DeliverySlot } from '../types';

export const MEALS: Meal[] = [
  {
    id: '1',
    name: 'Penne all\'Arrabbiata',
    description: 'Penne con salsa di pomodoro piccante, aglio e peperoncino fresco. Un classico della cucina romana.',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400',
    category: 'pasta',
    calories: 420,
    preparationTime: 20,
    ingredients: ['Penne', 'Pomodoro', 'Aglio', 'Peperoncino', 'Prezzemolo', 'Olio EVO'],
    allergens: ['Glutine'],
    rating: 4.7,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    id: '2',
    name: 'Salmone Teriyaki Bowl',
    description: 'Salmone grigliato con glassa teriyaki, riso basmati, edamame e avocado fresco.',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'fish',
    calories: 580,
    preparationTime: 25,
    ingredients: ['Salmone', 'Riso Basmati', 'Salsa Teriyaki', 'Avocado', 'Edamame', 'Sesamo'],
    allergens: ['Pesce', 'Soia'],
    rating: 4.9,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '3',
    name: 'Caesar Salad Premium',
    description: 'Lattuga romana, crostini croccanti, parmigiano reggiano, pollo grigliato e salsa Caesar.',
    price: 11.50,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400',
    category: 'salad',
    calories: 350,
    preparationTime: 15,
    ingredients: ['Lattuga Romana', 'Pollo', 'Parmigiano', 'Crostini', 'Salsa Caesar'],
    allergens: ['Glutine', 'Uova', 'Latte'],
    rating: 4.5,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '4',
    name: 'Margherita Napoletana',
    description: 'Pizza tradizionale con mozzarella di bufala DOP, pomodoro San Marzano e basilico fresco.',
    price: 10.90,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    category: 'pizza',
    calories: 680,
    preparationTime: 30,
    ingredients: ['Farina 00', 'Mozzarella di Bufala', 'Pomodoro San Marzano', 'Basilico', 'Olio EVO'],
    allergens: ['Glutine', 'Latte'],
    rating: 4.8,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '5',
    name: 'Vellutata di Zucca',
    description: 'Crema di zucca con semi tostati, olio al tartufo e crostini di pane integrale.',
    price: 8.90,
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400',
    category: 'soup',
    calories: 280,
    preparationTime: 35,
    ingredients: ['Zucca', 'Patate', 'Cipolla', 'Semi di Zucca', 'Olio al Tartufo'],
    allergens: ['Glutine'],
    rating: 4.6,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    id: '6',
    name: 'Tagliata di Manzo',
    description: 'Tagliata di manzo argentino con rucola, pomodorini e scaglie di Grana Padano.',
    price: 16.90,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400',
    category: 'meat',
    calories: 520,
    preparationTime: 25,
    ingredients: ['Manzo Argentino', 'Rucola', 'Pomodorini', 'Grana Padano', 'Olio EVO', 'Balsamico'],
    allergens: ['Latte'],
    rating: 4.8,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '7',
    name: 'Tiramisù Classico',
    description: 'Tiramisù preparato con mascarpone fresco, savoiardi, caffè espresso e cacao amaro.',
    price: 6.90,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
    category: 'dessert',
    calories: 380,
    preparationTime: 10,
    ingredients: ['Mascarpone', 'Savoiardi', 'Caffè', 'Uova', 'Cacao', 'Zucchero'],
    allergens: ['Glutine', 'Uova', 'Latte'],
    rating: 4.9,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '8',
    name: 'Açaí Power Bowl',
    description: 'Bowl di açaí con banana, granola, mirtilli, cocco e miele biologico.',
    price: 10.50,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
    category: 'breakfast',
    calories: 340,
    preparationTime: 10,
    ingredients: ['Açaí', 'Banana', 'Granola', 'Mirtilli', 'Cocco', 'Miele'],
    allergens: ['Frutta a guscio'],
    rating: 4.7,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: '9',
    name: 'Green Detox Smoothie',
    description: 'Smoothie depurativo con spinaci, mela verde, zenzero, limone e semi di chia.',
    price: 7.50,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
    category: 'smoothie',
    calories: 180,
    preparationTime: 5,
    ingredients: ['Spinaci', 'Mela Verde', 'Zenzero', 'Limone', 'Semi di Chia', 'Acqua di Cocco'],
    allergens: [],
    rating: 4.4,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: '10',
    name: 'Risotto ai Funghi Porcini',
    description: 'Risotto cremoso con funghi porcini trifolati, burro e parmigiano reggiano 24 mesi.',
    price: 13.90,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400',
    category: 'pasta',
    calories: 480,
    preparationTime: 30,
    ingredients: ['Riso Carnaroli', 'Funghi Porcini', 'Burro', 'Parmigiano', 'Cipolla', 'Brodo Vegetale'],
    allergens: ['Latte'],
    rating: 4.8,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '11',
    name: 'Poke Bowl Hawaiano',
    description: 'Tonno fresco marinato, riso sushi, mango, avocado, cipolla rossa ed edamame.',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'fish',
    calories: 450,
    preparationTime: 15,
    ingredients: ['Tonno', 'Riso Sushi', 'Mango', 'Avocado', 'Cipolla Rossa', 'Edamame', 'Salsa Ponzu'],
    allergens: ['Pesce', 'Soia'],
    rating: 4.6,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: '12',
    name: 'Pancakes con Frutti di Bosco',
    description: 'Pancakes soffici con sciroppo d\'acero, frutti di bosco freschi e panna montata.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
    category: 'breakfast',
    calories: 450,
    preparationTime: 15,
    ingredients: ['Farina', 'Uova', 'Latte', 'Frutti di Bosco', 'Sciroppo d\'Acero', 'Panna'],
    allergens: ['Glutine', 'Uova', 'Latte'],
    rating: 4.7,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Perfetto per iniziare il tuo percorso di alimentazione sana.',
    mealsPerWeek: 3,
    pricePerWeek: 29.90,
    pricePerMonth: 99.90,
    features: [
      '3 pasti a settimana',
      'Scelta dal menu completo',
      'Consegna gratuita',
      'Modifica ordini fino a 24h prima',
    ],
    isPopular: false,
    color: '#2EC4B6',
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Il piano più amato dai nostri clienti. Equilibrio perfetto.',
    mealsPerWeek: 5,
    pricePerWeek: 44.90,
    pricePerMonth: 159.90,
    features: [
      '5 pasti a settimana',
      'Scelta dal menu completo',
      'Consegna gratuita e prioritaria',
      'Modifica ordini fino a 12h prima',
      'Accesso a piatti esclusivi',
    ],
    isPopular: true,
    color: '#FF6B35',
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'Per chi vuole il massimo. Pasti gourmet ogni giorno.',
    mealsPerWeek: 7,
    pricePerWeek: 59.90,
    pricePerMonth: 209.90,
    features: [
      '7 pasti a settimana (1 al giorno)',
      'Menu completo + piatti gourmet',
      'Consegna gratuita e prioritaria',
      'Modifica ordini fino a 6h prima',
      'Piatti esclusivi dello chef',
      'Supporto nutrizionista dedicato',
    ],
    isPopular: false,
    color: '#FFD166',
  },
];

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Marco Rossi',
  email: 'marco.rossi@email.com',
  phone: '+39 333 1234567',
  address: 'Via Roma 42, 20121 Milano MI',
  subscription: {
    planId: 'standard',
    startDate: '2026-01-15',
    nextDelivery: '2026-02-20',
    isActive: true,
  },
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    items: [
      { meal: MEALS[0], quantity: 1 },
      { meal: MEALS[2], quantity: 1 },
      { meal: MEALS[6], quantity: 2 },
    ],
    total: 34.20,
    status: 'delivered',
    createdAt: '2026-02-10T10:30:00Z',
    deliveryDate: '2026-02-11T12:00:00Z',
    deliveryAddress: 'Via Roma 42, 20121 Milano MI',
  },
  {
    id: 'ORD-002',
    items: [
      { meal: MEALS[1], quantity: 1 },
      { meal: MEALS[4], quantity: 1 },
      { meal: MEALS[8], quantity: 1 },
    ],
    total: 31.30,
    status: 'delivered',
    createdAt: '2026-02-14T09:00:00Z',
    deliveryDate: '2026-02-15T12:00:00Z',
    deliveryAddress: 'Via Roma 42, 20121 Milano MI',
  },
  {
    id: 'ORD-003',
    items: [
      { meal: MEALS[3], quantity: 2 },
      { meal: MEALS[5], quantity: 1 },
    ],
    total: 38.70,
    status: 'preparing',
    createdAt: '2026-02-18T08:00:00Z',
    deliveryDate: '2026-02-19T12:00:00Z',
    deliveryAddress: 'Via Roma 42, 20121 Milano MI',
  },
];

export const DELIVERY_SLOTS: DeliverySlot[] = [
  { id: 'ds-1', date: '2026-02-20', timeRange: '11:00 - 13:00', available: true },
  { id: 'ds-2', date: '2026-02-20', timeRange: '13:00 - 15:00', available: true },
  { id: 'ds-3', date: '2026-02-20', timeRange: '18:00 - 20:00', available: false },
  { id: 'ds-4', date: '2026-02-21', timeRange: '11:00 - 13:00', available: true },
  { id: 'ds-5', date: '2026-02-21', timeRange: '13:00 - 15:00', available: true },
  { id: 'ds-6', date: '2026-02-21', timeRange: '18:00 - 20:00', available: true },
];
